name: Automatic Testing for Backend
on:
  push:
    branches:
      - main # Workflow will be triggered whenever there is a push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code from GitHub Repo
        uses: actions/checkout@v3

      - name: Setup Node.js in Ubuntu
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Remove existing node_modules folder from cloned project
        run: rm -rf ${{ github.workspace }}/node_modules/*

      - name: Navigate to the correct directory 
        run: cd backend && cd lambda_discover_service

      - name: Install dependencies based on package.json
        run: npm install

      - name: Run backend tests using Jest
        run: npm test
